version: '3.8'

services:
  # Jupyter Lab for data science
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks
      - ./src:/app/src
      - ./results:/app/results
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - datascience-net

  # Ollama for AI assistance
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - datascience-net

volumes:
  ollama_data:

networks:
  datascience-net:
    driver: bridge
