
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks
      - ./src:/app/src
      - ./results:/app/results
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - datascience-net

  # Ollama for AI assistance
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - datascience-net

  # Open WebUI
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3001:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - datascience-net

volumes:
  ollama_data:
  open_webui_data:

networks:
  datascience-net:
    driver: bridge